bluecellulab/cell/template.py
tests/test_cell/test_core.py

Removed the unreachable neuron_release_year<2014 check that simplified the template loading logic.

simplify template loading: remove unreachable condition

---

bluecellulab/circuit/config/simulation_config.py
setup.py

Although validating the circuit allows us to early-detect errors, it is becoming a performance bottleneck for simulations.
The circuit validator should be performed using snap before running the simulations.
snap has already a python api and a command line option for validating the circuit. There is no need to add a wrapper to it in bluecellulab (simulation level software)

disable snap's circuit validator for simulations

---

bluecellulab/cell/core.py
bluecellulab/ssim.py
setup.py

Based on @andrisecker' feedback.
* instantiate_gids' add_projections allows users to enable/disable projections defined in the **circuit** config, not simulation config.
* mark the forward skip arguments as [compatibility/non-sonata]
* Fixes in docstring rendering

Correction in SSim's docs

---

.github/workflows/release.yml
.github/workflows/test.yml

Currently the tests are run twice on main at the same time, this PR fixes it by changing the following:
* Release already triggers tests, tests won't need to be triggered explicitly.
* Push to main makes a release, tag does not need to trigger the release explicitly.

gh-actions: avoid duplicated runs by both release and test

---

bluecellulab/cell/core.py
bluecellulab/cell/template.py
tests/test_cell/test_core.py
tests/test_cell/test_template.py

Addresses #6 . 
* The order of template loading will not have a direct impact on the template naming.
* Cells loading the same template will have the same character lengths in their template names.
Additionally, by looking at the Python object, one can tell which underlying NEURON object it refers to.
```python
(Pdb) print(cell)
Cell Object: <bluecellulab.cell.core.Cell object at 0x7f86f325d690>.
NEURON ID: cADpyr_L2TPC_bluecellulab_0x7f86f03c2010.
(Pdb) cell.cell.hname()
'cADpyr_L2TPC_bluecellulab_0x7f86f03c2010[0]'
```

Simplify hoc template naming #6

---

bluecellulab/circuit/circuit_access.py

That message in essence should not be a warning message to confuse the users. It is only meaningful in debugging.

turn warning into log when alternate_morphologies is not present

---

bluecellulab/cell/core.py
bluecellulab/ssim.py

This function is very old and it is not used. External libraries also don't use. OpenGrok search does not show any match except for bglibpy/bluecellulab and their clones.
Our synapse representation nowadays is much more complicated. There is the synapse module for initiating synapses.
This addresses #80

remove cell::core::initialize_synapses, it's not used

---

bluecellulab/cell/core.py
bluecellulab/cell/injector.py
bluecellulab/cell/random.py
bluecellulab/cell/template.py
bluecellulab/importer.py
bluecellulab/synapse/synapse_types.py
bluecellulab/tools.py
bluecellulab/type_aliases.py
setup.py
tests/test_importer.py

This PR uses the modern NEURON API in dealing with the mechanisms loading. 
E.g. Bluecellulab previously was only checking for the x86_64, NEURON however supports a wider range of machine architectures such as: `platform.machine(), "i686", "x86_64", "powerpc", "umac"`.
* remove load_nrnmechanisms from tools, NEURON does it more comprehensively (e.g. https://github.com/neuronsimulator/nrn/blob/e0290762790622291c4867dee25a7c13e0c2d326/share/lib/python/neuron/__init__.py#L323)
* use neuron.load_mechanisms instead of neuron.h.nrn_load_dll, load_mechanisms is more comprehensive
* add type_aliases.py to annotate NEURON specific types
* remove nrn_disable_banner: no longer applicable
* Addresses #20 
* rename expected env var BGLIBPY_MOD_LIBRARY_PATH -> BLUECELLULAB_MOD_LIBRARY_PATH
* the env …

Update mechanisms loading using NEURON API

---

bluecellulab/rngsettings.py
bluecellulab/ssim.py
tests/test_rngsettings.py

Within the context of https://github.com/BlueBrain/BlueCelluLab/issues/75, I am debugging the random seed settings. 
I noticed there is this deprecated `base_noise_seed` still being passed around although it's not consumed by any function.
Config specifications and Neurodamus simulator deprecated that property long ago.
At the moment:
* BlueConfig specification does not have it: https://sonata-extension.readthedocs.io/en/latest/blueconfig.html
* SONATA specification does not have it: https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html
* NEURODAMUS does not have it: https://github.com/BlueBrain/neurodamus/
Bluecellulab should also not have it.

remove RNGSettings:base_noise_seed

---

bluecellulab/cell/core.py
bluecellulab/circuit/circuit_access.py
bluecellulab/ssim.py

Uses consistent argument names and argument types between add_replay_minis and add_replay_synapses.
It revealed base_seed argument required for add_replay_minis was not getting set by the SSim call. Now SSim intentionally passes a None (same behaviour as before, more explicit). This is possibly related to https://github.com/BlueBrain/BlueCelluLab/issues/75.

consistent arg names&types in replay minis&synapses

---

bluecellulab/__init__.py
bluecellulab/cell/core.py
bluecellulab/cell/section_distance.py
bluecellulab/cell/serialized_sections.py
bluecellulab/connection.py
bluecellulab/dendrogram.py
bluecellulab/plotwindow.py
bluecellulab/simulation/simulation.py
bluecellulab/ssim.py
bluecellulab/synapse/synapse_factory.py
bluecellulab/synapse/synapse_types.py
bluecellulab/tools.py
bluecellulab/type_aliases.py
tests/test_ballstick.py
tests/test_bglib.py
tests/test_cell/test_core.py
tests/test_load.py
tests/test_simulation/test_simulation.py
tests/test_synapse/test_synapse_factory.py
tests/test_tools.py
tests/test_ttx.py

This PR introduces a set of refactorings that aim to streamline and decouple `Synapse` objects from `Cell` objects, ensuring they only access the necessary data. It also enhances explicit typing for NeuronSection objects, improving type-checking reliability.
- **Limiting Synapse's Dependency on Cell:**
- **Motivation:** The extensive attributes and functions of the Cell object are not fully utilized by the Synapse objects.
- **Change:** Now, Synapse only retrieves the necessary hoc section and RNG settings from the Cell.
- **More explicit typing of Hoc parameters:**
- Explicitly type the NeuronSection objects. There were also type errors e.g. Optional[NeuronSection] instead of NeuronSection. Typing revealed them. The PR fixed them to avoid unreachable if obj is None checks.
- **Synapse …

Refactor: simplify the creation of Synapse objects #minor

---

README.rst

This pull request addresses the issue of the project banner not displaying correctly on PyPI. Initially, the readme utilized a relative path to reference the banner image, which worked within the repository but didn't translate correctly on PyPI's interface.

Update banner link for PyPI compatibility

---

bluecellulab/cell/core.py
bluecellulab/ssim.py
tests/test_cell/test_core.py

Some modules are following the blueconfig convention while some others follow the SONATA ones. 
This PR tries to use a consistent terminology across bluecellulab.
Type annotates the affected function signatures.
Creates `SynapseID` type to be used in function signatures.
Adds missing unit tests to the functions affected.
Deletes locate_bapsite method (not supported in the v6 hoc templates)
Deletes cell.hsynapses. It is accessible via cell.synapses[idx].hsynapse

Updating the terminology in api and docstring of Cell

---

bluecellulab/cell/core.py
bluecellulab/cell/injector.py
bluecellulab/tools.py

Previously bluecellulab was implementing a decorator for deprecating functions. `typing_extensions` has  a more detailed implementation of it. This PR replaced the built-in decorator with the `typing_extensions` one.
Here in the screenshot the IDE recognises that annotation and strikes through the deprecated code.
P.S. a relevant PEP is accepted. In Python 3.13 this decorator will be built-in.
https://peps.python.org/pep-0702/

use typing_extensions.deprecated decorator

---

.gitignore
bluecellulab/cell/core.py
bluecellulab/importer.py
bluecellulab/rngsettings.py
bluecellulab/ssim.py
bluecellulab/utils.py
tests/test_importer.py
tests/test_neuron_interpreter.py
tests/test_simulation/test_neuron_globals.py
tests/test_utils.py

Previously loading the hoc and mod files were taking place during `import bluecellulab`.
This was coupling every function in the API with the hoc and mods. With this change only the creation of `SSim`, `Cell` and `RNGSettings` objects is triggering the loading of mod and hoc files (once and only once).
Minis-validation tests pass:
```
py310: OK (125.48=setup[66.64]+cmd[11.43,47.41] seconds)
congratulations :) (125.69 seconds)
```
PSP-validation tests pass:
```
74 passed, 87 warnings in 334.98s (0:05:34) 
py310: OK (408.65=setup[68.46]+cmd[4.54,335.65] seconds)
congratulations :) (408.86 seconds)
```

Allow API functions to be used without loading hoc/mod #minor

---

bluecellulab/cell/core.py

Addresses the issues mentioned in https://github.com/BlueBrain/BlueCelluLab/issues/126.
* adds more information on the segx param
* adds default value for segx in `add_voltage_recording` and `get_voltage_recording`

Add default value for segx param, improve docs vcs: #minor

---

bluecellulab/circuit/config/sections.py

* make this forwards and backwards compatible
* see https://github.com/BlueBrain/libsonata/pull/345

libsonata has in the process of refactoring its module

---

CHANGELOG.rst
bluecellulab/cell/core.py
bluecellulab/cell/plotting.py
bluecellulab/cell/serialized_sections.py
bluecellulab/dendrogram.py
bluecellulab/psection.py
bluecellulab/psegment.py
bluecellulab/synapse/synapse_factory.py
tests/test_cell/test_core.py
tests/test_psection.py
tests/test_synapse/test_synapse_factory.py

+ Simplifies the NEURON sections representation in `Cell`.
+ The direct access to hsection option is removed. The access is through psection.
+ Addresses https://github.com/BlueBrain/BlueCelluLab/issues/128
+ solves the dependency issue between `init_psections` and `get_psections` (i.e. error if user wants to access get_psections without calling init_psections)
+ avoids storing lists of NEURON sections for each Cell. Instead turns them into property methods.
+ Removes the following attributes from `Cell`. Every functionality can be accomplished without storing these.
- secname_to_hsection
- secname_to_isec
- serialized
- cellname

Simplify psection representation in Cell

---

.github/workflows/release.yml

The coverage was only getting updated for the PR branches not main.
For security reasons when we call a workflow from the other we need to specify the env vars.
To upload the coverage of the main we do 2 workflow calls.
1) release.yml -> test.yml
2) test.yml -> codecov's workflow
Previously in 2, the secret is passed. In 1 it was not. Now both of them pass.

CI: pass CODECOV token in release->test workflow call

---

bluecellulab/cell/ballstick/__init__.py
bluecellulab/importer.py
tests/test_importer.py

pkg_resources is deprecated. 
https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources
https://importlib-resources.readthedocs.io/en/latest/migration.html

migrate pkg_resources -> importlib.resources

---

bluecellulab/importer.py
bluecellulab/tools.py
bluecellulab/utils.py
tests/test_tools.py
tests/test_utils.py

This should solve #4 . Could you check @arnaudon, @eleftherioszisis ?
You should be able to see the hoc specific outputs when logger mode is set to debug.
E.g.
```
DEBUG:bluecellulab.importer:Loaded Cell.hoc. stdout from the hoc: []
DEBUG:bluecellulab.importer:Loaded TDistFunc.hoc. stdout from the hoc: []
DEBUG:bluecellulab.importer:Loaded TStim.hoc. stdout from the hoc: []
```

Use CaptureOutput to forward hoc's stdout to logger.debug

---

pyproject.toml
tests/test_cell/test_core.py

It is an old pytest mark from the times some tests on large networks were requiring access to the data stored at the supercomputer.

rm debugtest mark, tests are equally debuggable

---

bluecellulab/circuit/circuit_access/bluepy_circuit_access.py
bluecellulab/circuit/synapse_properties.py
bluecellulab/synapse/synapse_factory.py
tests/test_synapse/test_synapse_factory.py
tox.ini

addresses "afferent_section_pos" / SynapseProperty.AFFERENT_SECTION_POS confusion across SONATA & bluepy implementations

Fix accessing afferent_section_pos of synapse description

---

MANIFEST.in
pyproject.toml

@mgeplf noticed the bluecellulab package is quite large.
This change excludes the /examples directory that is ~20MB.
The package size is reduced from 69MB to 48MB.
```
❯ dust                                                                                                                                                                            ─╯
4.6M         ┌── components                           │                                                                                   ░░░░░░░░░░░░░░░░░░░░░░░░░░░▓████████ │   7%
4.9M       ┌─┴ circuit_sonata_quick_scx_multi_circuit │                                                                                   ░░░░░░░░░░░░░░░░░░░░░░░░░░░█████████ │   7%
5.2M     ┌─┴ 2-sonata-network                         │ …
```

remove examples from package distribution

---

bluecellulab/simulation/parallel.py

This is to ensure all workers of `IsolatedProcess`s are going to be started via the `fork` mode, not the `spawn` mode.
Note: fork mode passes the parameters from the parent to child. Spawn does not (it leads to unexpected results when used with NEURON).
Source: https://github.com/neuronsimulator/nrn/issues/2842#issuecomment-2099841365

further restrict IsolatedProcess by setting multiprocessing start method

---

bluecellulab/analysis/inject_sequence.py
bluecellulab/stimulus/factory.py
tests/test_analysis/test_inject_sequence.py
tests/test_stimulus/test_factory.py

can choose to use `apply_multiple_stimuli` with amplitude based stimuli by passing raw amplitudes to `amplitudes` and setting `threshold_based` to `False`.

amplitude based stimuli in apply_multiple_stimuli

---

bluecellulab/psegment.py
bluecellulab/synapse/synapse_factory.py
tests/test_synapse/test_synapse_factory.py

When retrieving the synapse location through `syn_description`, we did not properly handle cases where the location is 0. In NEURON, you cannot insert a synapse or any point process at the start (position 0) or end (position 1) of a segment if it needs an ion e.g. na, k, ca, cl etc. The section location must be strictly within the bounds (0, 1), excluding both endpoints.

Fix: handle edge case in synapse location calculation with syn_description

---

bluecellulab/cell/core.py
bluecellulab/circuit/simulation_access.py
bluecellulab/stimulus/circuit_stimulus_definitions.py
tests/test_stimulus/test_circuit_stimulus_definitions.py

The `source` population field is no longer required for spike replay stimuli following the transition of synapse replay files to the h5 format.

Refactor: remove deprecated source population field in SynapseReplay

---

CONTRIBUTING.rst
README.rst
docs/source/contributing.rst
docs/source/index.rst

* added contributing file.
* mentioned the file on README
* added the contributing file to the documentation

add contributing guidelines

---

LICENSE
README.rst
examples/2-sonata-network/sonata-network.ipynb
examples/6-stimuli-sequence/stimuli-sequence.ipynb
examples/7-Extra-Simulation/Multiple-protocols.ipynb
examples/LICENSE
examples/README.rst
tests/LICENSE

Also fix https://github.com/BlueBrain/BlueCelluLab/issues/207 and address https://github.com/BlueBrain/BlueCelluLab/issues/206 to keep the main Apache software license intact and provide separate licenses for the morph and mod files in the test and examples directories as mentioned in the updated Readme

Add JOSS citation

---

bluecellulab/cell/template.py
tests/test_cell/test_core.py
tests/test_cell/test_template.py

Aims to address https://github.com/BlueBrain/BlueCelluLab/issues/209 by reducing template redefinition issues through the use of UUIDs instead of memory addresses. While not 100% collision-proof, this change improves uniqueness.

Replace memory addresses with UUIDs to enhance the uniqueness of template_name
